version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      # https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run:
          name: Halt if we don't need to publish
          command: |
              [ -n "$CI_INCREMENT_VERSION" ] || circleci-agent step halt
      - add_ssh_keys:
          fingerprints:
            - "76:57:0d:eb:5f:e0:e4:a4:3d:39:e0:6a:7b:4f:8c:76"
      - run: .circleci/publish
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
