version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*"
  publish:
    docker:
      - image: circleci/node:10.16
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      # - run: yarn publish --non-interactive
  increment-version:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "76:57:0d:eb:5f:e0:e4:a4:3d:39:e0:6a:7b:4f:8c:76"
      - run: .circleci/increment-version
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?/
            branches:
              ignore: /.*/
