#!/bin/bash

set -euxo pipefail

[[ $# == 2 && $2 =~ (prerelease|patch|minor|major) ]] || {
  echo "usage: $0 <branch-name> {prerelease|patch|minor|major}" 1>&2
  exit 1
}

branch="$1"
version="$2"

revision="$(git rev-parse $branch)"

data='{
  "revision": "'"$revision"'",
  "build_parameters": {
    "CIRCLE_JOB": "increment-version",
    "INCREMENT_VERSION": "'"$version"'"
  }
}'

token="45d0afedfb4c973dd06d856df8efcdaefff0b54b"

api_version="v1.1"
vcs_type="github"
username="ericfreese"
project="circle-ci-publish"

url="https://circleci.com/api/$api_version/project/$vcs_type/$username/$project/tree/$branch?circle-token=$token"

curl \
  -X POST \
  --header "Content-Type: application/json" \
  -d "$data" \
  $url
